### ISSUE TITLE
[Feature] Unbuild function

### ISSUE THREAD

**Issue by blaggacao** [nubark/facturark#12]
To provide true electronic invoicing experience, we need an unbuild function which would reverse the xml into a python dict of the corresponding API version. So that people can provide a XML or ZIP and the invoice will be auto populated with the provided values (as much as possible).

**Comment by blaggacao** [comment]
Would that mean: accompany every `def compose` with a something like a `def uncompose`?

**Comment by blaggacao** [comment]
Or is this a (hidden) API implemented in the `analyzer`?

**Comment by tebanep** [comment]
> Or is this a (hidden) API implemented in the `analyzer`?

The Analyzer in fact reverses an XML into Python data structures but it doesn't actually produces a full Python dict from its input. XML carries with it much more information that a simple naive json/dict could handle, so a baseline of what should be parsed must be established. I agree that facturark should have this functionality. Maybe, the component to be created could use the Analyzer underneath.

**Comment by blaggacao** [comment]
I don't dare to put it on my todo list, but if everything goes well, and I'm in a flow, who knows...
